<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kentico.Xperience.Admin" Version="31.9.0" />
    <PackageVersion Include="Kentico.Xperience.WebApp" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.azurestorage" Version="31.9.0" />
    <PackageVersion Include="kentico.xperience.imageprocessing" Version="31.9.0" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.35.0.4138" />
  </ItemGroup>
</Project>